INFO  | 06/28/2022 01:57:52 PM | File run_exp.py           | Line 26    | Writing log file to /home/alex/Projects/GRAN_social/exp/GRAN/FACEBOOK/log_exp_21714.txt
INFO  | 06/28/2022 01:57:52 PM | File run_exp.py           | Line 27    | Exp instance id = 21714
INFO  | 06/28/2022 01:57:52 PM | File run_exp.py           | Line 28    | Exp comment = None
INFO  | 06/28/2022 01:57:52 PM | File run_exp.py           | Line 29    | Config =
INFO  | 06/28/2022 01:57:56 PM | File gran_runner.py       | Line 135   | Train/val/test = 640/160/160
INFO  | 06/28/2022 01:57:57 PM | File gran_runner.py       | Line 148   | No Edges vs. Edges in training set = 33.46367918622637
ERROR | 06/28/2022 01:57:57 PM | File run_exp.py           | Line 46    | Traceback (most recent call last):
  File "/home/alex/Projects/GRAN_social/run_exp.py", line 42, in main
    runner.generate()
  File "/home/alex/Projects/GRAN_social/runner/gran_runner.py", line 455, in generate
    load_model(model, model_file, self.device)
  File "/home/alex/Projects/GRAN_social/utils/train_helper.py", line 48, in load_model
    model_snapshot = torch.load(file_name, map_location=device)
  File "/home/alex/anaconda3/envs/pytorch_graphs/lib/python3.10/site-packages/torch/serialization.py", line 712, in load
    return _load(opened_zipfile, map_location, pickle_module, **pickle_load_args)
  File "/home/alex/anaconda3/envs/pytorch_graphs/lib/python3.10/site-packages/torch/serialization.py", line 1049, in _load
    result = unpickler.load()
  File "/home/alex/anaconda3/envs/pytorch_graphs/lib/python3.10/site-packages/torch/serialization.py", line 1019, in persistent_load
    load_tensor(dtype, nbytes, key, _maybe_decode_ascii(location))
  File "/home/alex/anaconda3/envs/pytorch_graphs/lib/python3.10/site-packages/torch/serialization.py", line 1001, in load_tensor
    wrap_storage=restore_location(storage, location),
  File "/home/alex/anaconda3/envs/pytorch_graphs/lib/python3.10/site-packages/torch/serialization.py", line 970, in restore_location
    return default_restore_location(storage, map_location)
  File "/home/alex/anaconda3/envs/pytorch_graphs/lib/python3.10/site-packages/torch/serialization.py", line 175, in default_restore_location
    result = fn(storage, location)
  File "/home/alex/anaconda3/envs/pytorch_graphs/lib/python3.10/site-packages/torch/serialization.py", line 152, in _cuda_deserialize
    device = validate_cuda_device(location)
  File "/home/alex/anaconda3/envs/pytorch_graphs/lib/python3.10/site-packages/torch/serialization.py", line 136, in validate_cuda_device
    raise RuntimeError('Attempting to deserialize object on a CUDA '
RuntimeError: Attempting to deserialize object on a CUDA device but torch.cuda.is_available() is False. If you are running on a CPU-only machine, please use torch.load with map_location=torch.device('cpu') to map your storages to the CPU.

